### ISSUE TITLE
Undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [edas/simplenote2standardnote#1]
Thank you for your great work, but I'm getting the following error:

```
Traceback (most recent call last):
	3: from test.rb:66:in `<main>'
	2: from test.rb:66:in `map'
	1: from test.rb:67:in `block in <main>'
test.rb:17:in `convert': undefined method `strip' for nil:NilClass (NoMethodError)
```
Any ideas how I can fix it? Thank you for any guidance.

**Comment by mvance** [comment]
I'm running into the same issue. In case it might help, I'm running the following version of Ruby:

    ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

Thanks!

**Comment by johnny243** [comment]
I was taking a look at the script. The error is thrown after [this line](https://github.com/edas/simplenote2standardnote/blob/fce1210e62089fae78657ef9fcf708c6b76f2305/simplenote2standardnote.rb#L16):

```ruby
title, content = simplenote["content"].split("\r\n", 2)
```

Which is expecting that all your notes will have new line character after your title. If that's not the case, the above line will not assign a value to the `content` variable and only to the `title`.

On [line 17](https://github.com/edas/simplenote2standardnote/blob/fce1210e62089fae78657ef9fcf708c6b76f2305/simplenote2standardnote.rb#L17), the `strip` method is being called in a `NilClass` (which doesn't exist there).

---

You can solve it by:

1. Inserting `\r\n` after the title of your notes. Depending on how many notes you have, this will be easy to solve manually. If on the other hand you have lots of notes, please use the next workaround.
1. Put the following block of code after [line 16](https://github.com/edas/simplenote2standardnote/blob/fce1210e62089fae78657ef9fcf708c6b76f2305/simplenote2standardnote.rb#L16):

```ruby
if content.nil?
    content = title
    title = id
end
```

This will ensure there is a `content` and `title` (for the `title`, I used the note's ID. You could generate your own `title` if this does not fits your use case).

Let me know if that helps! :smile:

**Comment by Snazzyham** [comment]
Fwiw, @edas you're probably not maintaining this anymore, but @mvance @RareSnack if you, for some reason, 2 years later are still looking into a fix for this, I created a pull request featuring @johnny243 's code snippet as well as modified the array concatenation method.

**Comment by edas** [comment]
Oh ! Thx. 

I indeed do not maintain it anymore but let's merge the fix anyway.
